#!/usr/bin/env bash

set -euo pipefail

assert_installed()
{
	if ! hash "$1" &> /dev/null; then
		echo >&2 "$1 not installed"
		exit 1
	fi
}

assert_installed zipinfo
assert_installed diff

diff --side-by-side --left-column - <(zipinfo -1 "$1" | sort -f) <<-EOF && true
	task1/
	task1/Makefile
	task1/solution.txt
	task1/task1.c
	task2/
	task2/solution.txt
	task3/
	task3/even.c
	task3/even_odd_sum
	task3/Makefile
EOF

if [[ $? -eq 0 ]]; then
	echo -e "\nZip looks good!"
else
	echo -e "\nZip does not conform to assignment structure!"
fi
